// Code generated by protoc-gen-go.
// source: block.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	block.proto

It has these top-level messages:
	Block
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Block struct {
	PreviousHash     []byte  `protobuf:"bytes,1,req,name=PreviousHash" json:"PreviousHash,omitempty"`
	PublicKey        []byte  `protobuf:"bytes,2,req,name=PublicKey" json:"PublicKey,omitempty"`
	Nonce            *uint64 `protobuf:"varint,3,req,name=Nonce" json:"Nonce,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *Block) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Block) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*Block)(nil), "main.Block")
}

var fileDescriptor0 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xca, 0xc9, 0x4f,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xb2, 0xe7,
	0x62, 0x75, 0x02, 0x09, 0x0a, 0x89, 0x70, 0xf1, 0x04, 0x14, 0xa5, 0x96, 0x65, 0xe6, 0x97, 0x16,
	0x7b, 0x24, 0x16, 0x67, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xf0, 0x08, 0x09, 0x72, 0x71, 0x06, 0x94,
	0x26, 0xe5, 0x64, 0x26, 0x7b, 0xa7, 0x56, 0x4a, 0x30, 0x81, 0x85, 0x78, 0xb9, 0x58, 0xfd, 0xf2,
	0xf3, 0x92, 0x53, 0x25, 0x98, 0x81, 0x5c, 0x16, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xd2,
	0x6c, 0xeb, 0x54, 0x00, 0x00, 0x00,
}
